### ISSUE TITLE
Proposta alternatia per P1/Exe2

### ISSUE THREAD

**Issue by gmolinga** [Eudaldz/SOP#1]
ls -la | awk '{print $5}' retorna la llista dels bytes dels fitxers d'un directori. Això ho podríem fer serir com a opció alternatia per l'exercici2. Mira-t'ho i em dius algo.

**Comment by Eudaldz** [comment]
Crec que el operador '|' no el podem fer servir ja que és un 'pipe' (canonada) i crec recordar que el profe va dir que això ho veuriem a la practica 2.
